
version: "3.8"
services:
  jbc-validator:
    container_name: jbc-validator
    image: sigp/lighthouse
    user: root
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
    command:
      - lighthouse
      - vc
      - --beacon-nodes=https://metrabyte-cl.jibchain.net, https://jib-beacon.inan.in.th
      - --testnet-dir=/config
      - --init-slashing-protection
      - --graffiti=node555
      - --suggested-fee-recipient=0x0f44075b87f29CF4B0b3EE0110D2b1a43f71821C
      - --debug-level=info

